import React from 'react'
import type { AppProps } from 'next/app'
import CustomThemeProvider from '../styles'
import CssBaseline from '@mui/material/CssBaseline'
import PageLayout from '../react/components/PageLayout'
import Head from 'next/head'

function MyApp ({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Mais ouvidos do mês</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/spotify.ico" />
      </Head>
      <CustomThemeProvider>
        <CssBaseline />
        <PageLayout>
          <Component {...pageProps} />
        </PageLayout>
      </CustomThemeProvider>
    </>
  )
}

export default MyApp
