import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'

const Home: NextPage = () => {
  const router = useRouter()
  const authSpotifyUrl = 'https://accounts.spotify.com/authorize?client_id=3b588beb14524a86b378bb24e9df3b6f&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fseu-evento&scope=user-top-read'

  return (
    <div className={styles.container}>
      <Head>
        <title>Spotify project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <button onClick={() => router.push(authSpotifyUrl)}>
          clique aqui
        </button>
      </>
    </div>
  )
}

export default Home
